---
user         : amontgomery
winprofile   : Colours
linuxprofile : ""
herdrprofile : ""
macprofile   : ""
winapp       : "putty -load"
wintail      : ""
linuxapp: 'tmux new-window "ssh '
linuxtail: '|| read -n 1 -s"'
herdrapp: 'herd_ssh "'
macapp       : "itermtab.scpt"
mactail      : ""
#macapp       : "osascript -e 'tell application \"Terminal\" to do script \"ssh"
#mactail      : ";exit\"'"
rdpwin       : "mstsc /w:1024 /h:700 /V:"
rdplinux     : "rdesktop -g1500x900 "
macrdp       : "xfreerdp /w:1500 /h:900 /v:"
historysize  : 10

#macapp       : "osascript -e 'tell application \"Terminal\" to activate' -e 'tell application \"System Events\" to tell process \"Terminal\" to keystroke \"t\" using command down' -e 'tell application \"Terminal\" to do script \"ssh"

