---
user         : "amontgomery"
winprofile   : "Colours"
linuxprofile : ""
herdrprofile : ""
macprofile   : ""
winapp       : "putty -load"
wintail      : ""
linuxapp     : "tmux new-window \"ssh "
linuxtail    : "|| read -n 1 -s\""
herdrapp     : "herd_ssh \""
herdrtail    : ""
macapp       : "itermtab.scpt"
mactail      : ""
rdpwin       : "mstsc /w:1024 /h:700 /V:"
rdplinux     : "rdesktop -g1500x900 "
macrdp       : "xfreerdp /w:1500 /h:900 /v:"
historysize  : 10

